### ISSUE TITLE
support for multiome & ATAC

### ISSUE THREAD

**Issue by bjstewart1** [pachterlab/scATAK#1]
Great tool. 
One of the most useful elements as I see it is the tool defining a common list of accessible chromatin regions across all samples.
I have both 10X scATAC and 10X multiome data and in my case it would be useful to analyse the scATAC and the ATAC libraries from multiome together with scATAK.
The barcode whitelists are clearly a bit different for these two assays...
It might be useful to allow the chemistry/barcode for each sample to be specified in `-id --sample_id=sample_sheet.csv `

**Comment by gaofan83** [comment]
Thanks for your suggestion. Will work on that.

**Comment by gaofan83** [comment]
Please see whether version v1.1.0 can help you. Best.
