### ISSUE TITLE
combinatorial barcoding snATAC-seq data

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [pachterlab/scATAK#2]
Hi,

Thank you for creating the package, can this tool be used for pre-processing combinatorial barcoding snATAC-seq data? 

Best Regards,
Parul

**Comment by gaofan83** [comment]
Thanks for your interest. Are you talking about snapATAC data?

**Comment by Parul-Kudtarkar** [comment]
@gaofan83 since scATAK is meant for 10X dataset, we have our own combinatorial barcoding snATAC-seq dataset & are wondering if scATAK can be used with it.

**Comment by gaofan83** [comment]
The pipeline has just been updated. You are welcome to try v1.1.0 version if you have paired-end biological read files R1 &R3 as well as a cell barcode file R2. You can define your own whitelist file in sample_sheet.csv file.

**Comment by Parul-Kudtarkar** [comment]
Excellent! Thank you @gaofan83
