### ISSUE TITLE
Support for UMIs

### ISSUE THREAD

**Issue by dzhang12** [pachterlab/scATAK#3]
This package is working great for me, and I'd like to use it beyond just for 10X samples. Some scATAC-seq methods, especially multiomic scRNA/scATAC, such as paired-seq, snare-seq, etc., contain UMIs in the final libraries. Would scATAK be able to make use of them? Or do you expect and/or find that alignment-based de-duplication is adequate? Thank you!

**Comment by gaofan83** [comment]
We will need to do some benchmarking for paired-seq, snare-seq, etc. first.

**Comment by gaofan83** [comment]
If you are interested, please try our new pre-release (v1.2.0 and v1.3.0).
