### ISSUE TITLE
Support for M1 Mac OSX

### ISSUE THREAD

**Issue by cartal** [pachterlab/scATAK#4]
Hi! 

Thanks a lot for developing this tool, if this is similar to `bustools` this will help us a lot!

I was wondering if there is a plan to support this for users of the new Mac silicon computers. Since they are quire powerful, it would be a pity not to use `scATAK` there. Or is there a `conda` implementation I'm not aware of?

many thanks for any help with this. 

Regards

**Comment by gaofan83** [comment]
Thanks for your interest. As the executables in bin directory work for Linux environment only, the current workflow doesn't work for Mac. Maybe you want try under virtual linux environment?
